// version-react/src/components/products/Products.component.tsx
import { useDispatch } from "react-redux";
import { useAppSelector } from "../../state/app.hooks";
import { addProduct, removeProduct, selectProducts } from "../../state/product-state/product-slice";
import { addProductToCart, setProductInCartToSoldOut } from "../../state/cart-state/cart-slice";
import { useState } from "react";
import { IProduct } from "../../models/app.models";

function ProductsComponent() {
    const products = useAppSelector(selectProducts);
    const [productForm, setProductForm] = useState({
      name: '',
      description: '',
      price: -1
    });
    const [currentId, setCurrentId] = useState(6);
    const dispatch = useDispatch();

    function removeProductFromList(id: number) {
      dispatch(removeProduct({id: id}));
      dispatch(setProductInCartToSoldOut({id: id}));
    }

    function handleProductFormChange(event: any) {
      const name = event.target.name;
      const value = event.target.value;

      setProductForm(values => ({...values, [name]: value}));
    }

    function addnewProduct() {
      if (productForm.price as number > 0 
          && (productForm.name as string).trim().length > 0
          && (productForm.description as string).trim().length > 0) {
            
        var newProduct: IProduct = {
          id: currentId,
          name: productForm.name as string,
          description: productForm.description as string,
          price: productForm.price as number
        };

        setCurrentId(currentId+1);
        dispatch(addProduct({ product: newProduct }));
      }
    }

    const renderedProducts = products.map(product =>(
      <tr key={product.id}>
        <td> { product.id } </td>
        <td> { product.name } </td>
        <td> { product.description } </td>
        <td> { product.price } </td>
        <td> 
            <button className="btn btn-primary" onClick={() => dispatch(addProductToCart({product: product, quantity: 1}))}>Add product to cart</button> 
            <button className="btn btn-danger" onClick={() => removeProductFromList(product.id)}>Remove product from list</button>
        </td>
      </tr>
    ));

    return (
      <>
        <h1>Products</h1>
        
        <h3>Available products list</h3>
        <table className="table table-striped">
          <thead className="thead-dark">
              <tr>
                  <th>Id</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Price</th>
                  <th></th>
              </tr>
          </thead>
          <tbody>
              {renderedProducts}
          </tbody>
        </table>

        <h3>Add new product</h3>
        <form>
            <div className="mb-3">
                <label className="form-label me-3">Name: </label>
                <input name="name" type="text" value={productForm.name} onChange={handleProductFormChange}/>
            </div>
            <div className="mb-3">
                <label className="form-label me-3">Description: </label>
                <input name="description" type="text" value={productForm.description} onChange={handleProductFormChange}/>
            </div>
            <div className="mb-3">
                <label className="form-label me-3">Price: </label>
                <input name="price" type="number" value={productForm.price} onChange={handleProductFormChange}/>
            </div>
            <button className="btn btn-primary" type="button" onClick={addnewProduct}>Add new product</button>
        </form>
      </>
    );
  }
  
  export default ProductsComponent;

// version-angular/src/app/components/products/products.component.ts
import { Component } from "@angular/core";
import { FormBuilder, FormGroup } from "@angular/forms";
import { Store } from "@ngrx/store";
import { Observable } from "rxjs";
import { IProduct } from "src/app/models/app.models";
import { addProductToCart, setProductInCartToSoldOut } from "src/app/state/cart-state/cart.actions";
import { addProduct, removeProduct } from "src/app/state/products-state/products.actions";
import { selectProducts } from "src/app/state/products-state/products.selectors";

@Component({
    selector: 'products-component',
    templateUrl: './products.component.html'
  })

  export class ProductsComponent {
    products$: Observable<IProduct[]>;
    productForm: FormGroup;
    currentId: number = 6;

    constructor(private store: Store<any>, private formBuilder: FormBuilder) {
      this.products$ = this.store.select(selectProducts);
      this.productForm = this.formBuilder.group({
        name: '',
        description: '',
        price: -1
      });
    }

    addProductToCart(product: IProduct) {
      this.store.dispatch(addProductToCart({ product: product, quantity: 1}));
    }

    addnewProduct() {
      if (this.productForm.value.price as number > 0 
          && (this.productForm.value.name as string).trim().length > 0
          && (this.productForm.value.description as string).trim().length > 0) {

        var newProduct: IProduct = {
          id: this.currentId,
          name: this.productForm.value.name as string,
          description: this.productForm.value.description as string,
          price: this.productForm.value.price as number
        };

        this.currentId = this.currentId + 1;
        this.store.dispatch(addProduct({ product: newProduct }));
      }
    }
    
    removeProduct(id: number) {
      this.store.dispatch(removeProduct({ id: id }));
      this.store.dispatch(setProductInCartToSoldOut({ id: id }));
    }

  }
<h1>Products</h1>

<h3>Available products list</h3>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let product of products$ | async">
            <td> {{ product.id }} </td>
            <td> {{ product.name }} </td>
            <td> {{ product.description }} </td>
            <td> {{ product.price }} </td>
            <td> 
                <button class="btn btn-primary" (click)="addProductToCart(product)">Add product to cart</button> 
                <button class="btn btn-danger" (click)="removeProduct(product.id)">Remove product from list</button>
            </td>
        </tr>
    </tbody>
</table>

<h3>Add new product</h3>
<form [formGroup]="productForm" (ngSubmit)="addnewProduct()">
    <div class="mb-3">
        <label class="form-label me-3">Name: </label>
        <input id="name" type="text" formControlName="name">
    </div>
    <div class="mb-3">
        <label class="form-label me-3">Description: </label>
        <input id="description" type="text" formControlName="description">
    </div>
    <div class="mb-3">
        <label class="form-label me-3">Price: </label>
        <input id="price" type="number" formControlName="price">
    </div>
    <button class="btn btn-primary" type="submit">Add new product</button>
</form>
