// version-react/src/components/cart/Cart.component.tsx
import { useAppSelector } from "../../state/app.hooks";
import { selectCart, removeProductFromCart } from "../../state/cart-state/cart-slice";
import { useDispatch } from "react-redux";

function CartComponent() {
    const cart = useAppSelector(selectCart);
    const dispatch = useDispatch();

    const renderedCart = cart.map(cartItem =>(
      <tr key={cartItem.product.id}>
        <td> { cartItem.product.name } 
            <span style={{color: "red"}}>{ cartItem.available === false ? " (SOLD OUT)" : ""}</span>
        </td>
        <td> { cartItem.quantity } </td>
        <td>
            <button className="btn btn-danger" onClick={() => dispatch(removeProductFromCart({id: cartItem.product.id})) }>Remove product from cart</button>
        </td>
      </tr>
    ));

    return (
      <>
        <h1>Cart</h1>
        
        <h3>In Cart</h3>
        <table className="table table-sm table-striped">
          <thead className="thead-dark">
              <tr>
                  <th>Product name</th>
                  <th>Quantity</th>
                  <th></th>
              </tr>
          </thead>
          <tbody>
              {renderedCart}
          </tbody>
        </table>
      </>
    );
  }
  
  export default CartComponent;

// version-angular/src/app/components/cart/cart.component.ts
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';
import { removeProductFromCart } from '../../state/cart-state/cart.actions';
import { selectCart } from 'src/app/state/cart-state/cart.selectors';
import { ICartItem } from 'src/app/models/app.models';
import { Observable } from 'rxjs';

@Component({
  selector: 'cart-component',
  templateUrl: './cart.component.html'
})
export class CartComponent {
  cart$: Observable<ICartItem[]>;
 
  constructor(private store: Store<any>) {
    this.cart$ = this.store.select(selectCart);
  }
 
  removeProductFromCart(id: number) {
    this.store.dispatch(removeProductFromCart({ id: id }));
  }
}

<h1>Cart</h1>

<h2>In Cart</h2>
<div>
    <ul>
        <li *ngFor="let cartItem of cart$ | async">
            Product: {{ cartItem.product.name }},
            Quantity: {{ cartItem.quantity }}
            <span *ngIf="cartItem.available === false">, SOLD OUT</span>
            <button (click)="removeProductFromCart(cartItem.product.id)">Remove product from cart</button>
        </li>
    </ul>
</div>

<h2>Product list</h2>
<div>
    <ul>
        <li *ngFor="let product of products$ | async">
            Id: {{ product.id }},
            Name: {{ product.name }},
            Description: {{ product.description }},
            Price: {{ product.price }}
            <button (click)="addProductToCart(product)">Add product to cart</button>
        </li>
    </ul>
</div>
